// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using GNB.SalesEnquiry.Data.EF.SalesEnquiry.Context.Configurations;
using GNB.SalesEnquiry.Data.EF.SalesEnquiry.Models;
using Microsoft.EntityFrameworkCore;
#nullable disable

namespace GNB.SalesEnquiry.Data.EF.SalesEnquiry.Context
{
    public partial class SalesEnquiryContext : DbContext
    {
        public SalesEnquiryContext()
        {
        }

        public SalesEnquiryContext(DbContextOptions<SalesEnquiryContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Rates> Rates { get; set; }
        public virtual DbSet<Transactions> Transactions { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlite("Data Source=SalesEnquiry.db");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new RatesConfiguration());
            modelBuilder.ApplyConfiguration(new TransactionsConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
