// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GNB.SalesEnquiry.Data.EF.SalesEnquiry.Models
{
    public partial class Rates
    {
        public Guid RateId { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public decimal? Rate { get; set; }
    }
}