// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GNB.SalesEnquiry.Data.EF.SalesEnquiry.Models
{
    public partial class Transactions
    {
        public Guid TransactionId { get; set; }
        public string Sku { get; set; }
        public decimal? Amount { get; set; }
        public string Currency { get; set; }
    }
}