// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using GNB.SalesEnquiry.Data.EF.SalesEnquiry.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GNB.SalesEnquiry.Data.EF.SalesEnquiry.Context.Configurations
{
    public partial class RatesConfiguration : IEntityTypeConfiguration<Rates>
    {
        public void Configure(EntityTypeBuilder<Rates> entity)
        {
            entity.HasKey(e => e.RateId);

            entity.Property(e => e.RateId).ValueGeneratedNever();

            entity.Property(e => e.From)
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.Rate).HasColumnType("decimal(10, 2)");

            entity.Property(e => e.To)
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Rates> entity);
    }
}
