// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using GNB.SalesEnquiry.Data.EF.SalesEnquiry.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GNB.SalesEnquiry.Data.EF.SalesEnquiry.Context.Configurations
{
    public partial class TransactionsConfiguration : IEntityTypeConfiguration<Transactions>
    {
        public void Configure(EntityTypeBuilder<Transactions> entity)
        {
            entity.HasKey(e => e.TransactionId);

            entity.Property(e => e.TransactionId).ValueGeneratedNever();

            entity.Property(e => e.Amount).HasColumnType("decimal(10, 2)");

            entity.Property(e => e.Currency)
                .HasMaxLength(3)
                .IsFixedLength();

            entity.Property(e => e.Sku)
                .HasMaxLength(10)
                .IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Transactions> entity);
    }
}
